# Generated by Django 4.1.4 on 2023-01-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='בית ספר'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.classgroup', verbose_name='כיתה'),
        ),
    ]
