# Generated by Django 4.1.4 on 2023-02-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_student_options_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit1',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('avuri', models.TextField(verbose_name='להיות בן מצווה עבורי...')),
                ('egdal', models.CharField(max_length=100, verbose_name='כשאגדל אני רוצה להיות...')),
                ('photo_yaldut', models.ImageField(upload_to='', verbose_name='העלה תמונת ילדות')),
                ('tsipiot', models.TextField(verbose_name='הציפיות שלי מהמסע הן:')),
                ('photo_today', models.ImageField(upload_to='', verbose_name='העלה תמונה שלך היום')),
            ],
            options={
                'verbose_name': "תחנה א'",
                'verbose_name_plural': "תחנות א'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit10',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('erech_gallery', models.ImageField(upload_to='', verbose_name='העלו תמונות מתוך היצירה')),
                ('erech', models.TextField(verbose_name='מה למדתי מן התהליך ומדוע חשוב לקיים פעילות מסוג זה?')),
            ],
            options={
                'verbose_name': "תחנה י'",
                'verbose_name_plural': "תחנות י'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit11',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('reflacion', models.FileField(upload_to='', verbose_name='צרפו את הרפלקציה מתוך עבודת השורשים')),
                ('etgarim', models.TextField(verbose_name='ברפלקציה התייחסו לאתגרים בעבודתכם וגילויים חדשים')),
            ],
            options={
                'verbose_name': "תחנה יא'",
                'verbose_name_plural': "תחנות יא'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit12',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('sium_gallery', models.ImageField(upload_to='', verbose_name='העלו תמונות מפעילות הסיום עם ההורים')),
                ('sium', models.TextField(verbose_name='בפעילות הסיום התרגשתי מ.... ')),
            ],
            options={
                'verbose_name': "תחנה יב'",
                'verbose_name_plural': "תחנות יב'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit13',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('hergashti', models.TextField(verbose_name='במבט לאחור על המסע הרגשתי/ למדתי ש.....')),
            ],
            options={
                'verbose_name': 'תחנת סיום',
                'verbose_name_plural': 'תחנות סיום',
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit2',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('hitndavti', models.CharField(max_length=100, verbose_name="במהלך כיתה ו' התנדבתי ב...")),
                ('litrom', models.TextField(verbose_name='במה ארצה להתנדב /לתרום בשנה הבאה ומדוע?')),
                ('rosh', models.TextField(verbose_name='אם הייתי ראש ממשלת ישראל הייתי ...')),
            ],
            options={
                'verbose_name': "תחנה ב'",
                'verbose_name_plural': "תחנות ב'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit3',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('gil1', models.CharField(max_length=100, verbose_name="תקופה א'")),
                ('gil2', models.CharField(max_length=100, verbose_name="תקופה ב'")),
                ('gil3', models.CharField(max_length=100, verbose_name="תקופה ג'")),
                ('gil4', models.CharField(max_length=100, verbose_name="תקופה ד'")),
                ('avakesh1', models.TextField(verbose_name="תחנה משמעותיות שאבקש לי בעתיד א'")),
                ('avakesh2', models.TextField(verbose_name="תחנה משמעותיות שאבקש לי בעתיד ב'")),
            ],
            options={
                'verbose_name': "תחנה ג'",
                'verbose_name_plural': "תחנות ג'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit4',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('htsaga', models.TextField(verbose_name='מה אזכור מהטיולים וההצגות')),
                ('arachim', models.CharField(max_length=100, verbose_name='אילו ערכים באו לידי ביטוי?')),
            ],
            options={
                'verbose_name': "תחנה ד'",
                'verbose_name_plural': "תחנות ד'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit5',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('darsha_upload', models.FileField(upload_to='', verbose_name='העלה / העלי את הדרשה שלך')),
            ],
            options={
                'verbose_name': "תחנה ה'",
                'verbose_name_plural': "תחנות ה'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit6',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('sliha', models.TextField(verbose_name='אני שמחה שהצלחתי לבקש סליחה מ…')),
                ('salahti', models.TextField(verbose_name='אני גאה בעצמי שסלחתי ל…')),
            ],
            options={
                'verbose_name': "תחנה ו'",
                'verbose_name_plural': "תחנות ו'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit7',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('dmut1', models.TextField(verbose_name='דמות נשית משמעותית בחיי')),
                ('dmut2', models.TextField(verbose_name='דמות נשית המהווה השראה עבורי')),
            ],
            options={
                'verbose_name': "תחנה ז'",
                'verbose_name_plural': "תחנות ז'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit8',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('hitnadvti', models.TextField(verbose_name="במהלך כיתה ז' התנדבתי ב....")),
                ('lamadti', models.TextField(verbose_name='מה למדתי מהתנדבות זו?')),
                ('shana', models.TextField(verbose_name='במה ארצה להתנדב / לתרום בשנה הבאה ומדוע?')),
            ],
            options={
                'verbose_name': "תחנה ח'",
                'verbose_name_plural': "תחנות ח'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Exhibit9',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('giliti', models.TextField(verbose_name='בפעילות גיליתי שאני...')),
                ('erganno', models.TextField(verbose_name='מה אהבתי בפעילות שתנועות הנוער ארגנו לנו?')),
            ],
            options={
                'verbose_name': "תחנה ט'",
                'verbose_name_plural': "תחנות ט'",
            },
            bases=('journeys.exhibit',),
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_exhibit', models.PositiveSmallIntegerField(default=1)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('exhibit_1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit1')),
                ('exhibit_10', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit10')),
                ('exhibit_11', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit11')),
                ('exhibit_12', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit12')),
                ('exhibit_13', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit13')),
                ('exhibit_2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit2')),
                ('exhibit_3', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit3')),
                ('exhibit_4', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit4')),
                ('exhibit_5', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit5')),
                ('exhibit_6', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit6')),
                ('exhibit_7', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit7')),
                ('exhibit_8', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit8')),
                ('exhibit_9', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit9')),
            ],
        ),
    ]
