# Generated by Django 4.1.4 on 2023-02-12 13:49

from django.db import migrations, models
import django.db.models.deletion
import journeys.models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_alter_exhibit1_photo_today_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'verbose_name': 'מסע', 'verbose_name_plural': 'מסעות'},
        ),
        migrations.AlterField(
            model_name='exhibit1',
            name='photo_today',
            field=models.ImageField(upload_to=journeys.models.user_directory_path, verbose_name='העלה תמונה שלך היום'),
        ),
        migrations.AlterField(
            model_name='exhibit10',
            name='erech_gallery',
            field=models.ImageField(upload_to=journeys.models.user_directory_path, verbose_name='העלו תמונות מתוך היצירה'),
        ),
        migrations.AlterField(
            model_name='exhibit11',
            name='reflacion',
            field=models.FileField(upload_to=journeys.models.user_directory_path, verbose_name='צרפו את הרפלקציה מתוך עבודת השורשים'),
        ),
        migrations.AlterField(
            model_name='exhibit12',
            name='sium_gallery',
            field=models.ImageField(upload_to=journeys.models.user_directory_path, verbose_name='העלו תמונות מפעילות הסיום עם ההורים'),
        ),
        migrations.AlterField(
            model_name='exhibit5',
            name='darsha_upload',
            field=models.FileField(upload_to=journeys.models.user_directory_path, verbose_name='העלה / העלי את הדרשה שלך'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='exhibit_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit1'),
        ),
    ]
