# Generated by Django 4.1.4 on 2023-03-08 19:15

from django.db import migrations, models
import django.db.models.deletion
import journeys.models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_alter_journey_options_alter_exhibit1_photo_today_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit0',
            fields=[
                ('exhibit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journeys.exhibit')),
                ('my_name', models.CharField(max_length=100, verbose_name='שמי')),
                ('name_origin', models.CharField(max_length=100, verbose_name='מקור שמי')),
                ('born_date_loazi', models.CharField(max_length=100, verbose_name='נולדתי בתאריך עברי')),
                ('born_date_ivri', models.CharField(max_length=100, verbose_name='נולדתי בתאריך לועזי')),
                ('parents_names', models.CharField(max_length=100, verbose_name='שמות הוריי')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='מקום הולדתי')),
                ('my_photo', models.ImageField(upload_to=journeys.models.user_directory_path, verbose_name='העלה תמונה שלך')),
            ],
            options={
                'verbose_name': 'הקדמה',
                'verbose_name_plural': 'הקדמות',
            },
            bases=('journeys.exhibit',),
        ),
        migrations.AlterField(
            model_name='journey',
            name='current_exhibit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journey',
            name='exhibit_0',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journeys.exhibit0'),
        ),
    ]
