# Generated by Django 4.1.4 on 2023-01-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_options_alter_teacher_options'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'verbose_name': 'כיתה', 'verbose_name_plural': 'כיתות'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'שכבה', 'verbose_name_plural': 'שכבות'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'בית ספר', 'verbose_name_plural': 'בתי ספר'},
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='מספר'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.teacher', verbose_name='מורה'),
        ),
    ]
